<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Secure TV Preview</title>
    <style>
        body {
            margin: 0;
            padding: 20px;
            font-family: Arial, sans-serif;
            background: #1a1a1a;
            color: white;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding: 20px;
            background: #2d2d2d;
            border-radius: 10px;
        }
        .preview-frame {
            width: 100%;
            height: 80vh;
            border: 2px solid #444;
            border-radius: 10px;
            background: black;
        }
        .loading {
            text-align: center;
            padding: 50px;
            font-size: 18px;
        }
        .error {
            color: #ff6b6b;
            text-align: center;
            padding: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Secure TV Preview</h1>
            <p>Content is loaded securely from protected source</p>
        </div>
        <div id="preview-container">
            <div class="loading">Loading secure content...</div>
        </div>
    </div>

    <script>
        // Configuration
        const CONFIG = {
            proxyEndpoint: '/.netlify/functions/proxy-content'
        };

        // Secure content loading function
        async function loadSecureContent() {
            try {
                const response = await fetch(CONFIG.proxyEndpoint);
                
                if (!response.ok) {
                    throw new Error(`HTTP error! status: ${response.status}`);
                }
                
                const htmlContent = await response.text();
                
                // Create secure iframe with restricted permissions
                const iframe = document.createElement('iframe');
                iframe.className = 'preview-frame';
                iframe.sandbox = "allow-scripts allow-same-origin allow-forms allow-popups";
                iframe.srcdoc = htmlContent;
                
                document.getElementById('preview-container').innerHTML = '';
                document.getElementById('preview-container').appendChild(iframe);
                
            } catch (error) {
                showError('Error loading content: ' + error.message);
                console.error('Loading error:', error);
            }
        }

        function showError(message) {
            document.getElementById('preview-container').innerHTML = 
                '<div class="error">' + message + '</div>';
        }

        // Initialize when page loads
        document.addEventListener('DOMContentLoaded', loadSecureContent);
    </script>
</body>
</html>
